import Head from 'next/head'
import { use, useEffect, useState } from "react";
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { useRouter } from "next/router";
import styles from "./index.module.scss";
import AuthService from "../services/auth.service"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const router = useRouter()



  const [userForm, setUserForm] = useState({
      email: "",
      password: ""
  });

  const [message, setMessage] = useState("")

  const handleInput = (e) => {
      setUserForm({ ...userForm, [e.target.name]: e.target.value });
  }

  const submitForm = (e) => {
      e.preventDefault();
      AuthService.login(userForm)
          .then((data) => {
          if (!data.token) {
              setMessage("User not found");
              console.log(message);
              return false;
          } 
          console.log(data.token)
          localStorage.setItem('token', data.token);
          router.push("/ressources");
          })
          .catch(
              (err) => {
                  setMessage(err);
              }
          )
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.login__wrapper}>

          <div className={styles.logo}>
            <img src="/logo_axa.webp" />
          </div>

          <div className={styles.form}>
            <h1 className={styles.page__title}>Connexion</h1>
              <form>
                  <div class={styles.input__wrapper}>
                      <label>Email</label>
                      <input 
                          type="text" 
                          placeholder="Email" 
                          name="email" 
                          value={userForm.email} 
                          onChange={(e) => {
                              handleInput(e);
                          }}
                      />
                  </div>
                  <div class={styles.input__wrapper}>
                      <label>Mot de passe</label>
                      <input 
                          type="password" 
                          placeholder="Mot de passe" 
                          name="password" 
                          value={userForm.password} 
                          onChange={(e) => {
                              handleInput(e);
                          }}
                      />
                  </div>
                  {message ? ( 
                    <>
                    <p className={styles.error}>{message}</p>
                    </>
                  ) : (
                    ""
                  )
                }
                  <button type="submit" onClick={(e) => {submitForm(e)}}>Se connecter</button>
              </form>
          </div>
      </div>
      </main>
    </>
  )
}
